### ISSUE TITLE
API returned unexpected result, 401

### ISSUE THREAD

**Issue by nardstae** [olivierhagolle/Sentinel-download#11]
Hi,

Any chance you can help me with this?

```
sentinel search --sentinel2 -s 20160201 -e 20160211 <u> <p> vienna_bbox.geojson

Error: API returned unexpected response 401 .
Traceback (most recent call last):
  File "/usr/local/bin/sentinel", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentinelsat/scripts/cli.py", line 99, in search
    for product in api.get_products():
  File "/usr/local/lib/python2.7/site-packages/sentinelsat/sentinel.py", line 129, in get_products
    raise ValueError('API response not valid. JSON decoding failed.')
ValueError: API response not valid. JSON decoding failed.
```

Thanks!

**Comment by olivierhagolle** [comment]
Sorry, probably wrong repository
Olivier
